M48
; DRILL file {KiCad 7.0.9} date Thu Nov 16 15:57:46 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-16T15:57:46+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0398
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0882
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0988
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.1260
%
G90
G05
T1
X2.4409Y-2.2047
X2.4409Y-2.4016
T2
X3.0205Y-1.748
X3.4205Y-1.748
T3
X3.3421Y-2.2039
X3.4209Y-2.1539
X3.4209Y-2.2539
T4
X2.599Y-1.7461
T5
X2.599Y-1.5689
T6
X2.4622Y-1.9866
X3.9547Y-1.9807
T0
M30
